version = 3.7.14
runner.dialect = scala212
align.preset = more
assumeStandardLibraryStripMargin = true
indent.main = 2
indent.significant = 4
lineEndings = unix
optIn.annotationNewlines = true
maxColumn = 100
newlines.implicitParamListModifierForce = [before]
rewrite.rules = [SortImports]
rewrite.redundantBraces.generalExpressions = false
trailingCommas = keep
