akka.loggers = ["akka.event.slf4j.Slf4jLogger"]
# Weirdly, this is necessary in tests
akka.logger-startup-timeout = 30s


conversation-service {
  bind-address = ${THRIFT_LISTEN_ADDRESS}
}

rpc {
  organization = ${ORG_SERVICE_HOST}

  telephony = ${TELEPHONY_SERVICE_HOST}

  stats = ${STATISTICS_SERVICE_HOST}

  presence = ${PRESENCE_SERVICE_HOST}

  queue = ${QUEUE_SERVICE_HOST}

  email = ${EMAIL_SERVICE_HOST}

  tags = ${TAGS_SERVICE_HOST}

  podio = ${PODIO_SERVICE_HOST}

  integrations = ${INTEGRATIONS_SERVICE_HOST}

  offer = ${OFFER_SERVICE_HOST}

  conversation-transfer = ${CONVERSATION_TRANSFER_SERVICE_HOST}

  facebook-messenger = ${FACEBOOK_MESSENGER_SERVICE_HOST}

  smooch = ${SMOOCH_SERVICE_HOST}

  search = ${SEARCH_SERVICE_HOST}
}

dynamodb {
  access-key-id = ${DYNAMODB_ACCESS_KEY_ID}
  secret-key = ${DYNAMODB_SECRET_KEY}
  endpoint-url = ${DYNAMODB_ENDPOINT_URL}
}

sqs {
  aws-key = ${AWS_ACCESS_KEY_ID}
  aws-secret = ${AWS_SECRET_ACCESS_KEY}
  endpoint = ${SQS_ENDPOINT_URL}

}

redis {
  host = ${REDIS_HOST}
}

kafka-publisher {
  bootstrap-servers = ${CLOUDKARAFKA_BOOTSTRAP_SERVERS}
  scram-username = ${CLOUDKARAFKA_SCRAM_USERNAME}
  scram-password = ${CLOUDKARAFKA_SCRAM_PASSWORD}
  schema-registry-urls = ${CLOUDKARAFKA_SCHEMA_REGISTRY_URLS}
}