package com.dixa.twilio.model.messaging.repository

import CountryCapability.AlphanumericSenderSupport.{No, PreRegistrationRequired, Yes}
import com.dixa.twilio.model.phonenumber.{CountryCallingCode => CCC}

private[repository] object HardcodedCountryAlphanumericCapabilities {

  private[repository] val countryCodeToCapabilityMap: Map[CCC, CountryCapability] = {
    val asList = List(
      CountryCapability(CCC(30), "Greece", Yes),
      CountryCapability(CCC(31), "Netherlands", Yes),
      CountryCapability(CCC(32), "Belgium", No),
      CountryCapability(CCC(33), "France", Yes),
      CountryCapability(CCC(34), "Spain", Yes),
      CountryCapability(CCC(39), "Italy", Yes),
      CountryCapability(CCC(40), "Romania", PreRegistrationRequired), // TODO optional
      CountryCapability(CCC(41), "Switzerland", Yes),
      CountryCapability(CCC(43), "Austria", Yes),
      CountryCapability(CCC(44), "United Kingdom", Yes),
      CountryCapability(CCC(45), "Denmark", Yes),
      CountryCapability(CCC(46), "Sweden", Yes),
      CountryCapability(CCC(47), "Norway", Yes),
      CountryCapability(CCC(48), "Poland", Yes),
      CountryCapability(CCC(49), "Germany", Yes),
      CountryCapability(CCC(55), "Brazil", PreRegistrationRequired),
      CountryCapability(CCC(61), "Australia", PreRegistrationRequired),
      CountryCapability(CCC(62), "Indonesia", PreRegistrationRequired),
      CountryCapability(CCC(64), "New Zealand", No),
      CountryCapability(CCC(65), "Singapore", PreRegistrationRequired),
      CountryCapability(CCC(81), "Japan", Yes),
      CountryCapability(CCC(94), "Sri Lanka", PreRegistrationRequired),
      CountryCapability(CCC(95), "Myanmar", PreRegistrationRequired),
      CountryCapability(CCC(213), "Algeria", Yes),
      CountryCapability(CCC(216), "Tunisia", PreRegistrationRequired), // TODO conditional
      CountryCapability(CCC(220), "Gambia", Yes),
      CountryCapability(CCC(221), "Senegal", Yes),
      CountryCapability(CCC(222), "Mauritania", Yes),
      CountryCapability(CCC(223), "Mali", Yes),
      CountryCapability(CCC(224), "Guinea / Papua New Guinea", Yes),
      CountryCapability(CCC(226), "Burkina Faso", Yes),
      CountryCapability(CCC(227), "Niger", Yes),
      CountryCapability(CCC(228), "Togo", Yes),
      CountryCapability(CCC(229), "Benin", PreRegistrationRequired),
      CountryCapability(CCC(230), "Mauritius", Yes),
      CountryCapability(CCC(231), "Liberia", PreRegistrationRequired),
      CountryCapability(CCC(232), "Sierra Leone", Yes),
      CountryCapability(CCC(233), "Ghana", PreRegistrationRequired),
      CountryCapability(CCC(234), "Nigeria", PreRegistrationRequired),
      CountryCapability(CCC(235), "Chad", Yes),
      CountryCapability(CCC(236), "Central African Republic", Yes),
      CountryCapability(CCC(237), "Cameroon", PreRegistrationRequired),
      CountryCapability(CCC(238), "Cape Verde", Yes),
      CountryCapability(CCC(239), "Sao Tome and Principe", Yes),
      CountryCapability(CCC(240), "Equatorial Guinea", Yes),
      CountryCapability(CCC(241), "Gabon", Yes),
      CountryCapability(CCC(242), "Gongo", Yes),
      CountryCapability(CCC(244), "Angola", Yes),
      CountryCapability(CCC(245), "Guinea-Bissau", PreRegistrationRequired),
      CountryCapability(CCC(248), "Seychelles", Yes),
      CountryCapability(CCC(249), "Sudan", PreRegistrationRequired),
      CountryCapability(CCC(250), "Rwanda", PreRegistrationRequired),
      CountryCapability(CCC(251), "Ethiopia", PreRegistrationRequired),
      CountryCapability(CCC(252), "Somalia", Yes),
      CountryCapability(CCC(255), "Ivory Coast (Côte d'Ivoire)", PreRegistrationRequired),
      CountryCapability(CCC(256), "Uganda", PreRegistrationRequired),
      CountryCapability(CCC(257), "Burundi", Yes),
      CountryCapability(CCC(258), "Mozambique", Yes),
      CountryCapability(CCC(260), "Zambia", PreRegistrationRequired),
      CountryCapability(CCC(261), "Madagascar", Yes),
      CountryCapability(CCC(262), "Mayotte and Réunion", Yes),
      CountryCapability(CCC(263), "Zimbabwe", Yes),
      CountryCapability(CCC(264), "Namibia", Yes),
      CountryCapability(CCC(265), "Malawi", Yes),
      CountryCapability(CCC(266), "Lesotho", Yes),
      CountryCapability(CCC(267), "Botswana", Yes),
      CountryCapability(CCC(268), "Swaziland", PreRegistrationRequired),
      CountryCapability(CCC(269), "Comoros", Yes),
      CountryCapability(CCC(297), "Aruba", Yes),
      CountryCapability(CCC(298), "Faroe Islands", Yes),
      CountryCapability(CCC(299), "Greenland", Yes),
      CountryCapability(CCC(350), "Gibraltar", Yes),
      CountryCapability(CCC(351), "Portugal", Yes),
      CountryCapability(CCC(352), "Luxembourg", Yes),
      CountryCapability(CCC(353), "Ireland", Yes),
      CountryCapability(CCC(354), "Iceland", Yes),
      CountryCapability(CCC(355), "Albania", Yes),
      CountryCapability(CCC(357), "Cyprus", Yes),
      CountryCapability(CCC(358), "Finland", Yes),
      CountryCapability(CCC(359), "Bulgaria", Yes),
      CountryCapability(CCC(365), "Malta", Yes),
      CountryCapability(CCC(370), "Lithuania", Yes),
      CountryCapability(CCC(371), "Latvia", Yes),
      CountryCapability(CCC(372), "Estonia", Yes),
      CountryCapability(CCC(373), "Moldova", Yes),
      CountryCapability(CCC(374), "Armenia", PreRegistrationRequired),
      CountryCapability(CCC(376), "Andorra", Yes),
      CountryCapability(CCC(378), "San Marino", Yes),
      CountryCapability(CCC(383), "Kosovo", Yes),
      CountryCapability(
        CCC(381),
        "Serbia",
        PreRegistrationRequired
      ), // TODO change to prereg optional
      CountryCapability(CCC(382), "Montenegro", Yes),
      CountryCapability(CCC(385), "Croatia", Yes),
      CountryCapability(CCC(386), "Slovenia", Yes),
      CountryCapability(CCC(387), "Bosnia and Herzegovina", Yes),
      CountryCapability(CCC(389), "North Macedonia", Yes),
      CountryCapability(CCC(421), "Slovakia", Yes),
      CountryCapability(CCC(423), "Liechtenstein", Yes),
      CountryCapability(CCC(500), "Falkland Island", Yes),
      CountryCapability(CCC(501), "Belize", Yes),
      CountryCapability(CCC(502), "Guatemala", Yes),
      CountryCapability(CCC(507), "Panama", No),
      CountryCapability(CCC(508), "Saint Pierre and Miquelon", Yes),
      CountryCapability(CCC(509), "Haiti", Yes),
      CountryCapability(CCC(590), "Guadeloupe", Yes),
      CountryCapability(CCC(591), "Bolivia", Yes),
      CountryCapability(CCC(592), "Guyana", Yes),
      CountryCapability(CCC(595), "Paraguay", No),
      CountryCapability(CCC(597), "Suriname", Yes),
      CountryCapability(CCC(596), "Martinique", Yes),
      CountryCapability(CCC(599), "Curaçao", Yes),
      CountryCapability(CCC(670), "Timor-Leste", Yes),
      CountryCapability(CCC(673), "Brunei Darussalam", Yes),
      CountryCapability(CCC(674), "Nauru", No),
      CountryCapability(CCC(676), "Tonga", Yes),
      CountryCapability(CCC(677), "Solomon Islands", Yes),
      CountryCapability(CCC(678), "Vanuatu", Yes),
      CountryCapability(CCC(679), "Fiji", Yes),
      CountryCapability(CCC(682), "Cook Islands", Yes),
      CountryCapability(CCC(685), "Samoa", Yes),
      CountryCapability(CCC(686), "Kiribati", Yes),
      CountryCapability(CCC(689), "French Polynesia", Yes),
      CountryCapability(CCC(691), "Micronesia", Yes),
      CountryCapability(CCC(692), "Marshall Islands", Yes),
      CountryCapability(CCC(853), "Macao", Yes),
      CountryCapability(CCC(855), "Cambodia", PreRegistrationRequired),
      CountryCapability(CCC(856), "Laos (Lao People's Democratic Republic)", Yes),
      CountryCapability(CCC(880), "Bangladesh", PreRegistrationRequired),
      CountryCapability(CCC(960), "Maldives", Yes),
      CountryCapability(CCC(961), "Lebanon", Yes),
      CountryCapability(CCC(963), "Syrian Arab Republic", No),
      CountryCapability(CCC(964), "Iraq", Yes),
      CountryCapability(
        CCC(966),
        "Saudi Arabia",
        PreRegistrationRequired
      ), // TODO special case, Conditional
      CountryCapability(CCC(967), "Yemen", Yes),
      CountryCapability(CCC(968), "Oman", PreRegistrationRequired),
      CountryCapability(
        CCC(972),
        "Israel",
        PreRegistrationRequired
      ), // TODO special case, partial preregistration, Conditional
      CountryCapability(CCC(973), "Bahrain", Yes),
      CountryCapability(CCC(975), "Bhutan", Yes),
      CountryCapability(CCC(993), "Turkmenistan", Yes),
      CountryCapability(CCC(994), "Azerbaijan", Yes),
      CountryCapability(CCC(995), "Georgia", Yes),
      CountryCapability(CCC(977), "Nepal / Palau", PreRegistrationRequired),
      CountryCapability(CCC(992), "Tajikistan", Yes),
      CountryCapability(CCC(998), "Uzbekistan", Yes),
      CountryCapability(CCC(1242), "Bahamas", No),
      CountryCapability(CCC(1246), "Barbados", Yes),
      CountryCapability(CCC(1264), "Anguilla", Yes),
      CountryCapability(CCC(1268), "Antigua and Barbuda", Yes),
      CountryCapability(CCC(1345), "Cayman Islands", No),
      CountryCapability(CCC(1441), "Bermuda", Yes),
      CountryCapability(CCC(1473), "Grenada", Yes),
      CountryCapability(CCC(1649), "Turks and Caucos Islands", Yes),
      CountryCapability(CCC(1664), "Montserrat", Yes),
      CountryCapability(CCC(1767), "Dominica", Yes),
      CountryCapability(CCC(1784), "Saint Lucia / Saint Vincent and the Grenadines", Yes),
      CountryCapability(CCC(1829), "Dominican Republic", No),
      CountryCapability(CCC(1868), "Trinidad and Tobago", Yes),
      CountryCapability(CCC(1869), "Saint Kitts and Nevis", Yes),
      CountryCapability(CCC(1876), "Jamaica", Yes),
      CountryCapability(CCC(380), "Ukraine", Yes),
      CountryCapability(CCC(1684), "American Samoa", Yes),
      CountryCapability(CCC(54), "Argentina", Yes),
      CountryCapability(CCC(243), "Congo (Democratic Republic of the Congo)", Yes),
      CountryCapability(CCC(253), "Djibouti", Yes),
      CountryCapability(CCC(504), "Honduras", Yes),
      CountryCapability(CCC(441481), "Guernsey", Yes),
      CountryCapability(CCC(441624), "Isle of Man", Yes),
      CountryCapability(CCC(441534), "Jersey", Yes),
      CountryCapability(CCC(218), "Libya", Yes),
      CountryCapability(CCC(377), "Monaco", Yes),
      CountryCapability(CCC(976), "Mongolia", Yes),
      CountryCapability(CCC(687), "New Caledonia", Yes),
      CountryCapability(CCC(92), "Pakistan", Yes),
      CountryCapability(CCC(970), "Palestine", Yes),
      CountryCapability(CCC(1340), "Virgin Islands (British Virgin Islands)", Yes),
    )
    asList.map(cCap => cCap.countryCallingCode -> cCap).toMap
  }
}
// no - Canada, Chile, China, Colombia, Costa Rica, Ecuador, El Salvador, French Guiana, Guam, Hungary, India, Kyrgyzstan, Malaysia, Nicaragua, Peru, Puerto Rico, South Africa, South Korea, Taiwan, Uruguay, United States, Russia

// prereg - Afghanistan, Belarus, Congo (Republic of the Congo), Cuba, Czech Republic, Egypt, Guinea, Hong Kong, Iran, Jordan, Kazakhstan, Kenya, Kuwait, Mexico(special?), Morocco, Philippines, Qatar, Vietnam, Venezuela, United Arab Emirates, Turkey, Thailand, Tanzania,
// South Sudan,
