name: Update Dependency Graph
'on':
  push:
    branches:
      - master
      - main
      - develop
  schedule:
    - cron: 0 9 * * 1-5
env:
  MAVEN_REPO_USER: ${{ secrets.MAVEN_REPO_USER }}
  MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWORD }}
jobs:
  update-graph:
    name: Update Dependency Graph
    runs-on: backend-jvm-ss
    steps:
      - uses: actions/checkout@v3
      - uses: scalacenter/sbt-dependency-submission@v2
        with:
          working-directory: ./
          configs-ignore: scala-doc-tool scala-tool