name: 'twilio-client'

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]
    types: [opened, reopened, synchronize]

jobs:
  build-test:
    if: ${{ !endsWith(github.ref,'/master')
    uses: dixahq/github-actions/.github/workflows/sbt-release.yml@main
    secrets: inherit
    with:
      sbt_task: '"+test"'
  release:
    if: ${{ endsWith(github.ref,'/master')
    uses: dixahq/github-actions/.github/workflows/sbt-release.yml@main
    secrets: inherit
    with:
      sbt_task: '"release with-defaults"'

